/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto1prograiii;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author emanu
 */
public class CrearPersona extends javax.swing.JDialog {

    /**
     * Creates new form CrearPersona
     */
    public CrearPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Añadir nueva Persona");
        redimensionar();
        EmpezarTextfields("Pulsa aqui para guardar tu nombre", "Pulsa aqui para guardar tu primer apellido", "Pulsa aqui para guardar tu segundo apellido", "Aqui va tu Carne", "Aqui pones que tan viejo estas","Aqui pones tu DNI, apenas para ir a verte en el Regiistro civil" );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProfesor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFName = new javax.swing.JTextField();
        jTFA1 = new javax.swing.JTextField();
        jTXA2 = new javax.swing.JTextField();
        jTXages = new javax.swing.JTextField();
        jTXCarne = new javax.swing.JTextField();
        jTFDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/CrearPersona.jpg"))); // NOI18N
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 705, 523));

        jProfesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bienvenido al sistema de creación de profesores");
        jProfesor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 620, -1));

        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matricula de esta prestigiosa Universidad");
        jPanelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 218, -1));

        jButton1.setText("Guardar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelDatos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 458, -1, -1));

        jLabel3.setText("Nombre");
        jPanelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 58, -1));

        jLabel4.setText("Primer Apellido:");
        jPanelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, -1, -1));

        jLabel5.setText("Segundo Apelllido");
        jPanelDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, -1, -1));

        jLabel6.setText("Edad");
        jPanelDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, -1, -1));

        jLabel7.setText("Carnet");
        jPanelDatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 217, -1, -1));

        jLabel8.setText("Cedula:");
        jPanelDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, -1, -1));

        jTFName.setText("jTextField1");
        jTFName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNameMouseClicked(evt);
            }
        });
        jTFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNameActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 57, -1, -1));

        jTFA1.setText("jTextField1");
        jTFA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFA1MouseClicked(evt);
            }
        });
        jTFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFA1ActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTFA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 97, -1, -1));

        jTXA2.setText("jTextField3");
        jTXA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXA2MouseClicked(evt);
            }
        });
        jTXA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXA2ActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTXA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 137, -1, -1));

        jTXages.setText("jTextField4");
        jTXages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXagesMouseClicked(evt);
            }
        });
        jTXages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXagesActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTXages, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 177, -1, -1));

        jTXCarne.setText("jTextField5");
        jTXCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXCarneMouseClicked(evt);
            }
        });
        jTXCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXCarneActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTXCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 217, -1, -1));

        jTFDNI.setText("jTextField6");
        jTFDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFDNIMouseClicked(evt);
            }
        });
        jTFDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDNIActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTFDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 257, -1, -1));

        jLabel9.setText("Tipo de persona a matricular:");
        jPanelDatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulsa aqui y selecciona alguna de las opciones", "Profesor", "Alumno" }));
        jPanelDatos.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 319, 218, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTFNameActionPerformed

    private void jTFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFA1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTFA1ActionPerformed

    private void jTXA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXA2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTXA2ActionPerformed

    private void jTXagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXagesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTXagesActionPerformed

    private void jTXCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXCarneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTXCarneActionPerformed

    private void jTFDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDNIActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTFDNIActionPerformed

    private void jTFNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNameMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTFName);
    }//GEN-LAST:event_jTFNameMouseClicked

    private void jTFA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFA1MouseClicked
        // TODO add your handling code here:
         cerrarjTextfielsds(jTFA1);
    }//GEN-LAST:event_jTFA1MouseClicked

    private void jTXA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXA2MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTXA2);
    }//GEN-LAST:event_jTXA2MouseClicked

    private void jTXagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXagesMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTXages);
    }//GEN-LAST:event_jTXagesMouseClicked

    private void jTXCarneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXCarneMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTXCarne);
    }//GEN-LAST:event_jTXCarneMouseClicked

    private void jTFDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFDNIMouseClicked
        // TODO add your handling code here:
         cerrarjTextfielsds(jTFDNI);
         
    }//GEN-LAST:event_jTFDNIMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardar();
        mostrarpanelmatricula();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearPersona dialog = new CrearPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jProfesor;
    private javax.swing.JTextField jTFA1;
    private javax.swing.JTextField jTFDNI;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTextField jTXA2;
    private javax.swing.JTextField jTXCarne;
    private javax.swing.JTextField jTXages;
    // End of variables declaration//GEN-END:variables

    private void redimensionar() {
        ImageIcon icon = new ImageIcon("C:\\Users\\emanu\\OneDrive\\Personal\\Documentos de Microsoft Word\\Documents\\NetBeansProjects\\Proyecto1PrograIII\\Proyecto1PrograIII\\src\\Multimedia\\CrearPersona.jpg");
Image image = icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
icon = new ImageIcon(image);
jLabel1.setIcon(icon);

    }

    private void EmpezarTextfields(String Mensaje1, String Mensaje2, String Mensaje3, String Mensaje4, String Mensaje5, String Mensaje6) {
        jTFName.setText(Mensaje1);
        jTFA1.setText(Mensaje2);
        jTXA2.setText(Mensaje3);
        jTFDNI.setText(Mensaje6);
        jTXages.setText(Mensaje4);
        jTXCarne.setText(Mensaje5);
    }
    private void cerrarjTextfielsds(JTextField componente){
        componente.setText("");
    }

    private void guardar() {
        //Franco o Harold, no sé quien va a hacer el Backend, pero aqui va el método que guarda los datos
        
    }

    private void mostrarpanelmatricula() {
        Object Opcion = jComboBox1.getSelectedItem();
        String option = (String) Opcion;
        if(option.equals("Profesor")){
            empezarProfesor();
        }
    }

    private void empezarProfesor() {
        jPanelFondo.setVisible(false);
    }
}
