/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1prograiii;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author emanu
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        reescalar();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateBTN = new javax.swing.JButton();
        Verbtn = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        EraseBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateBTN.setBackground(new java.awt.Color(0, 0, 29));
        CreateBTN.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        CreateBTN.setText("Crear ➕");
        CreateBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CreateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 100));

        Verbtn.setText("Ver 👁️👁️");
        Verbtn.setPreferredSize(new java.awt.Dimension(72, 23));
        jPanel1.add(Verbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 100));

        UpdateBTN.setText("Actualizar ");
        jPanel1.add(UpdateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 100));

        EraseBTN.setText("Eliminar 🗑️");
        EraseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseBTNActionPerformed(evt);
            }
        });
        jPanel1.add(EraseBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 110, 100));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EraseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EraseBTNActionPerformed

    private void CreateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBTNActionPerformed
        // TODO add your handling code here:
        CrearPersona cp = new CrearPersona (null, true);
        cp.setVisible(true);
    }//GEN-LAST:event_CreateBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBTN;
    private javax.swing.JButton EraseBTN;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton Verbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void reescalar() {
        ImageIcon icon = new ImageIcon("C:\\Users\\emanu\\OneDrive\\Personal\\Documentos de Microsoft Word\\Documents\\NetBeansProjects\\Proyecto1PrograIII\\src\\Multimedia\\walpapersql.jpg");
Image image = icon.getImage().getScaledInstance(1280, 720, Image.SCALE_SMOOTH);
icon = new ImageIcon(image);
jLabel1.setIcon(icon);
jLabel1.setText("");
this.setTitle("UniManage");
this.setDefaultCloseOperation(3);
this.setLocationRelativeTo(null);

    }
}
